try{
    printem()
}catch(err){
    console.log(err)
}finally{
    console.log('finally block')
}